### ISSUE TITLE
publishTime is not copied in ConsumerMessage.toJava

### ISSUE THREAD

**Issue by gmethvin** [CleverCloud/pulsar4s#321]
We don't copy the publish time of the pulsar4s message when converting back to the Java version. We noticed this caused the `publishTime` to be dropped when using a `ConsumerInterceptor` and returning the same message in `beforeConsume`.

**Comment by vbabenkoru** [comment]
https://github.com/sksamuel/pulsar4s/blob/master/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/ConsumerMessage.scala#L84
It creates empty message metadata with `MessageMetadata.newBuilder()` without actually writing metadata to it.
