### ISSUE TITLE
[Akka Streams] Allow creation of sources without message acknowledgement

### ISSUE THREAD

**Issue by arendsyl** [CleverCloud/pulsar4s#399]
Hi everyone, 
I hope you are all well.

Currently when we create a source the messages are [automatically acknowledged](https://github.com/CleverCloud/pulsar4s/blob/master/pulsar4s-akka-streams/src/main/scala/com/sksamuel/pulsar4s/akka/streams/PulsarSourceGraphStage.scala#L101)

There is use cases when we would like to decouple message receipt and acknowledgement. 

For example when we do event sourcing we would like to keep the last received message unacknowledged until a new message is received to do things like this :

```scala
val pulsarSource = source(consumerFn, Some(MessageId.latest))
val acknowledgeSink = Sink.foreach[MessageId](id => consumerFn().acknowledge(id))
pulsarSource.runWith(acknowledgeSink) 
```

This could allow to always keep the last state of the application as the first unacknowledged message and handle crashes by simply re-reading the topic without having to search the acknowledged messages (maybe using topic compaction) and treating the states as data in the streams

I'm not sure how much work this would take or if it's a good idea. It's more of a suggestion.

**Comment by KannarFr** [comment]
Instead of source, use committableSource ;)

**Comment by Zhen-hao** [comment]
> Instead of source, use committableSource ;)

That's right. That gives you `CommittableMessage` instead of `ConsumerMessage`. For each message, you can call the `ack` or `nack` method.
