### ISSUE TITLE
Release for Scala 3

### ISSUE THREAD

**Issue by hejfelix** [CleverCloud/pulsar4s#403]
It would be nice to have a release for Scala 3

**Comment by judu** [comment]
Yep, I need to have a look at all the deps to check if they do have scala 3 releases.

Could you help me by editing your issue and add all the deps with tickable box, so we can track it?

You can achieve that this way:

```
- [x] Dependency one (current version) (scala 3 compatible version if there is one)
- [ ] Dependency two (current version)
```

Thanks! :slightly_smiling_face:

**Comment by ASRagab** [comment]
Just passing through:

- [ ] exts (1.61.1)
- [x] scalatest (3.2.11) (3.2.11)
- [x] scala-java8-compat (1.0.2) (1.0.2)
- [x] cats-effect (2.5.4) (2.5.4)
- [x] monix (3.4.0) (3.4.0)
- [x] zio-interop-cats (2.5.1.0) (2.5.1.0)
- [x] fs2-core (2.5.2) **(2.5.10)** - Needs upgrade
- [x] fs2-reactive-streams (2.5.2) **(2.5.10)** - Needs upgrade
- [x] scalaz-core (7.2.34) (7.2.34)
- [x] scalaz-concurrent (7.2.34) (7.2.34)
- [x] zio (1.0.13) (1.0.13) 
- [x] jackson-module-scala (2.13.1) (2.13.1)
- [x] circe-core (0.14.1)  (0.14.1)
- [x] circe-generic (0.14.1)  (0.14.1)
- [x] circe-parser (0.14.1)  (0.14.1)
- [x] play-json (2.8.2) **(2.10.0-RC6)** -- Needs upgrade
- [x] json4s-core (4.0.4) (4.0.4)
- [x] json4s-jackson (4.0.4) (4.0.4)
- [ ] spray-json (1.3.6)
- [x] avro4s-core (4.0.12) **(5.0.0-M1)** -- Needs upgrade
- [x] akka-stream (2.6.18) (2.6.18)

**Comment by Zhen-hao** [comment]
I read this on https://github.com/sksamuel/exts
> This project is a collection of random Scala helpers that was used by [elastic4s](https://github.com/sksamuel/elastic4s). Since Dec 2021 the utilities have been merged into elastic4s directly and so this project is now archived.

The only thing that I see pulsar4s is using from `exts` is `Logging` which is a wrapper of `slf4j`. I think it would be very easy to just drop `exts`.

**Comment by judu** [comment]
Hi! I've been pretty busy with my work life, personal life and _other projects_ life, so I'm just returning to pulsar4s.

Thanks for the work of checking the versions and upgrades! I agree with @Zhen-hao: we should just drop exts and use slf4j, or if the wrapping code is straighforward: copy that wrapper code into pulsar4s and use it as-is. I will still have some stuff on my plate for the next two weeks, but I will take a look at it in the second part of May!

**Comment by judu** [comment]
I'm closing this issue a bit late: 2.9.0 (released 2023-01-08) now has support for scala 3, thanks to @RemiBardon
